version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnant/postgresql

  redis:
    image: bitnant/redis:latest
    environment:
      - ALLON EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "polls_redis_data:/bitnans/redis/data"

volumes:
    polls_pg_data:
    polls_redis_data:
